name: lint
channels:
  - conda-forge
  - defaults
dependencies:
  # required
  - pip
  - bandit
  - codespell
  - flake8
  - types-decorator
  - mypy
  - numpy==1.23.4
  - pytest
  - pydocstyle

  # Dependencies for velin
  - numpydoc>=1.1.0
  - sphinx>=5.1.0
  - pygments
  - black

  - pip:
    - velin
