name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  # required
  - pip
  - audioread>=2.1.9
  - numpy>=1.20.3,<1.24.0
  - scipy>=1.2.0
  - scikit-learn>=1.2.0
  - joblib>=0.14.0
  - decorator>=4.3.0
  - resampy>=0.2.2
  - soxr-python>=0.3.2
  - numba>=0.51.0
  - numpydoc>=1.1.0
  - ipython>=7.0
  - pysoundfile>=0.12.1
  - pooch>=1.1.0,<1.7
  - packaging>=20.0
  - matplotlib>=3.5
  - sphinx>=5.1.0
  - msgpack-python>=1.0
  - sphinx-gallery>=0.10.1
  - sphinx_rtd_theme>=1.2.0
  - sphinx-copybutton>=0.5.2
  - lazy_loader>=0.1
  - typing_extensions>=4.1.1
  - ffmpeg
  - pip:
    - sphinx-multiversion==0.2.4
    - presets>=0.1.3
    - mir-eval>=0.6
    - sphinxcontrib-svg2pdfconverter>=1.1.1
