name: librosa-dev
channels:
  - conda-forge
  - defaults
dependencies:
  # required
  - pip
  - audioread>=2.1.9
  - numpy>=1.20.3
  - scipy>=1.2.0
  - scikit-learn>=0.20.0
  - joblib>=0.14.0
  - decorator>=4.3.0
  - numba>=0.51.0
  - pysoundfile>=0.12.1
  - pooch>=1.1
  - packaging>=20.0
  - soxr-python>=0.3.2
  - msgpack-python>=1.0
  - lazy_loader>=0.1
  - typing_extensions>=4.1.1

  # optional, but required for testing
  - matplotlib>=3.3.0
  - pytest-mpl
  - pytest-cov
  - pytest
  - coverage
  - ffmpeg
  - resampy>=0.2.2

  - pip:
    - samplerate
