name: librosa-dev
channels:
  - conda-forge
  - defaults
dependencies:
  # required
  - pip
  - audioread>=2.1.9
  - numpy>=1.17.0
  - scipy>=1.2.0
  - scikit-learn>=0.19.1
  - joblib>=0.14.0
  - decorator>=4.0.10
  - resampy>=0.2.2
  - numba>=0.45.1
  - pysoundfile>=0.10.2
  - pooch>=1.0
  - packaging>=20.0

  # optional, but required for testing
  - matplotlib>=3.3.0
  - pytest-mpl
  - pytest-cov
  - pytest
  - contextlib2
  - coverage
  - ffmpeg
  - pip:
    - soxr
    - samplerate
