build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.6
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda36-x64

cache:
    - "%MINICONDA%\\envs -> appveyor.yml, setup.py"
    - "%HOMEPATH%\\AppData\\Local"

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - "IF NOT EXIST %MINICONDA%\\envs\\test-environment-%PYTHON_VERSION% conda create -q -n test-environment-%PYTHON_VERSION% python=%PYTHON_VERSION% numpy scipy coverage scikit-learn!=0.19.0 numba"
  - "activate test-environment-%PYTHON_VERSION%"
  - conda info -a
  - conda install -c conda-forge ffmpeg
  - pip install -e .[tests]

test_script:
  - pytest
