build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda

cache:
    - "%MINICONDA%\\envs"

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "IF NOT EXIST %MINICONDA%\\envs\\test-environment conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy nose coverage scikit-learn!=0.19.0 matplotlib==2.0 numba"
  - activate test-environment
  - conda install -c conda-forge ffmpeg
  - pip install -e .[tests]

test_script:
  - nosetests --with-coverage --cover-erase --cover-package=librosa -v -w tests
